version: '3'
services:
  app:
    image: golang:latest
    container_name: chess-engine
    working_dir: /app
    volumes:
      - ./ChessEngine:/app
    ports:
      - "8080:8080"
    command: go run ./cmd
