version: '3'
services:
  app:
    image: golang:latest # Replace with the Go Docker image you need
    container_name: chess-bot
    working_dir: /app
    volumes:
      - .:/app # Map your Go application code into the container
    ports:
      - "8080:8080" # Map your application's port to the host machine
    command: go run ./cmd # Replace with the command to start your Go application
